<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <RootNamespace>artifact.desktop</RootNamespace>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <ApplicationDefinition Remove="App.xaml" />
	    <Page Include="App.xaml" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
      <PackageReference Include="MaterialDesignColors" Version="5.3.3-ci1349" />
      <PackageReference Include="MaterialDesignThemes" Version="5.3.3-ci1349" />
      <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="log4net.config" />
      <Content Include="log4net.config">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <None Remove="appsettings.json" />
      <Content Include="appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="appsettings.development.json" />
      <Content Include="appsettings.development.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\..\CSharp\Laboratory\Logging\Logging.csproj" />
      <ProjectReference Include="..\..\..\..\CSharp\Laboratory\Utils\Utils.csproj" />
      <ProjectReference Include="..\artifact.shared\artifact.shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Page Update="Views\MainWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="Views\SingleImage\SingleImageView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>
</Project>
